services:
  app:
    container_name: typescript-app
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.prod}
    image: nubank-capital-gains
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    stdin_open: true
    tty: true
    command: bash
