version: "3.8"

services:
  app:
    container_name: typescript-app
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.prod}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    command: ${COMMAND:-"node dist/main.js"}
