services:
  app:
    container_name: typescript-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nubank-capital-gains
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm run dev
